### ISSUE TITLE
No module named 'vision_msgs'

### ISSUE THREAD

**Issue by AtharzWang** [NVIDIA-AI-IOT/ros2_deepstream#3]
When I installed the dependencies and use command ' ros2 run single_stream_pkg single_stream --ros-args -p input_source:="/dev/video0"', some errors happened: No module named 'vision_msgs'.
How could I do?

**Comment by AsawareeBhide** [comment]
Hi! Could you please confirm if you've installed [vision_msgs](https://github.com/ros-perception/vision_msgs/tree/ros2) correctly?

**Comment by AsawareeBhide** [comment]
Try: `sudo apt-get install ros-eloquent-vision-msgs`

**Comment by Floria-Xu** [comment]
Have u fix the problem?I face the same one~Should I download ROS

**Comment by AtharzWang** [comment]
> 

yes, thanks @AsawareeBhide. It works.
